# LightTwinSVM Program - Simple and Fast
# Version: 0.2.0-alpha - 2018-05-30
# Developer: Mir, A. (mir-am@hotmail.com)
# License: GNU General Public License v3.0

# Configuration file for building and testing LightTwinSVM on Travis CI

# Ubuntu 14.04.5 LTS
dist: trusty 
sudo: true

branches:
  only:
  - master

language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'

addons:
  apt:
    packages:
    - liblapack-dev
    - libblas-dev
    - python3-dev
    - python3-tk

before_install:
  - chmod +x install-travisci.sh
  - echo $'#!/bin/bash\npython3 src/test_program.py -f' > ltsvm_test.sh
  - chmod +x ltsvm_test.sh

install: ./install-travisci.sh

script:
- ./ltsvm_test.sh
