# LightTwinSVM Program - Simple and Fast
# Version: 0.1.0-alpha - 2018-05-24
# Developer: Mir, A. (mir-am@hotmail.com)
# License: GNU General Public License v3.0

language: python
python:
- "3.6"

-before_install:
- sudo apt-get install python3-tk python3-dev liblapack-dev libblas-dev -y

install:
- pip install -r requirments.txt
- git clone -b 8.500.x --single-branch https://github.com/conradsnicta/armadillo-code.git temp
- c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` ./src/optimizer/clippdcd.cpp -o ./src/clippdcd`python3-config --extension-suffix` -I ./temp/include -DARMA_DONT_USE_WRAPPER -lblas -llapack 

script:
- ls -al src